import js from "@eslint/js";
import typescript from "@typescript-eslint/eslint-plugin";
import typescriptParser from "@typescript-eslint/parser";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import prettier from "eslint-plugin-prettier";

export default [
  js.configs.recommended,
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        console: "readonly",
        document: "readonly",
        window: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLAudioElement: "readonly",
        HTMLFormElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLOptionElement: "readonly",
        HTMLLabelElement: "readonly",
        HTMLSpanElement: "readonly",
        HTMLAnchorElement: "readonly",
        Document: "readonly",
        Element: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        React: "readonly",
        fetch: "readonly",
        URL: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        AbortController: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        indexedDB: "readonly",
        IDBDatabase: "readonly",
        IDBObjectStore: "readonly",
        IDBTransaction: "readonly",
        IDBRequest: "readonly",
        IDBKeyRange: "readonly",
        IDBOpenDBRequest: "readonly",
        IDBCursor: "readonly",
        IDBCursorWithValue: "readonly",
        IDBIndex: "readonly",
        IDBVersionChangeEvent: "readonly",
        Range: "readonly",
        Selection: "readonly",
        Response: "readonly",
        Request: "readonly",
        Headers: "readonly",
        crypto: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        performance: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        EventTarget: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        PointerEvent: "readonly",
        TouchEvent: "readonly",
        DragEvent: "readonly",
        ClipboardEvent: "readonly",
        FocusEvent: "readonly",
        InputEvent: "readonly",
        WheelEvent: "readonly",
        AnimationEvent: "readonly",
        TransitionEvent: "readonly",
        ProgressEvent: "readonly",
        ErrorEvent: "readonly",
        MessageEvent: "readonly",
        PopStateEvent: "readonly",
        HashChangeEvent: "readonly",
        StorageEvent: "readonly",
        PageTransitionEvent: "readonly",
        SecurityPolicyViolationEvent: "readonly",
        PromiseRejectionEvent: "readonly",
        BeforeUnloadEvent: "readonly",
        XMLHttpRequest: "readonly",
        WebSocket: "readonly",
        Worker: "readonly",
        SharedWorker: "readonly",
        ServiceWorker: "readonly",
        Notification: "readonly",
        MediaQueryList: "readonly",
        MediaQueryListEvent: "readonly",
        AudioContext: "readonly",
        Image: "readonly",
        ImageData: "readonly",
        CanvasRenderingContext2D: "readonly",
        WebGLRenderingContext: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        atob: "readonly",
        btoa: "readonly",
        structuredClone: "readonly",
        queueMicrotask: "readonly",
        reportError: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        open: "readonly",
        close: "readonly",
        print: "readonly",
        getComputedStyle: "readonly",
        matchMedia: "readonly",
        scrollTo: "readonly",
        scrollBy: "readonly",
        focus: "readonly",
        blur: "readonly",
        getSelection: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": typescript,
      react,
      "react-hooks": reactHooks,
      prettier,
    },
    rules: {
      // Prettier
      "prettier/prettier": "error",

      // TypeScript
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",

      // React
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      "react/jsx-uses-react": "off",
      "react/jsx-uses-vars": "error",

      // React Hooks
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",

      // General
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-unused-vars": "off", // Use TypeScript's version
    },
    settings: {
      react: {
        version: "detect",
      },
    },
  },
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "*.config.js",
      "*.config.ts",
      "src/foliate-js/**",
    ],
  },
];
